FROM jupyter/scipy-notebook

# docker build -t localhost:5000/dlcc/jupyter-singleuser:latest files/jupyter-docker-stacks/single-user/

MAINTAINER Ivan Suftin <isuftin@usgs.gov>

CMD ["/usr/local/bin/start-singleuser.sh"]
